//! Shared test utilities for NeuroWealth Vault tests

use crate::*;
use soroban_sdk::{
    contract, contractimpl, contracttype,
    testutils::{Address as _, Events},
    Address, Env, Symbol, Val, Vec,
};

// ============================================================================
// SIMPLE TEST TOKEN CONTRACT
// ============================================================================

#[contracttype]
enum TokenDataKey {
    Balance(Address),
}

#[contract]
pub struct TestToken;

#[contractimpl]
impl TestToken {
    pub fn mint(env: Env, to: Address, amount: i128) {
        let balance: i128 = env
            .storage()
            .persistent()
            .get(&TokenDataKey::Balance(to.clone()))
            .unwrap_or(0);
        env.storage()
            .persistent()
            .set(&TokenDataKey::Balance(to), &(balance + amount));
    }

    pub fn transfer(env: Env, from: Address, to: Address, amount: i128) {
        from.require_auth();
        assert!(amount > 0, "amount must be positive");

        let from_balance: i128 = env
            .storage()
            .persistent()
            .get(&TokenDataKey::Balance(from.clone()))
            .unwrap_or(0);
        assert!(from_balance >= amount, "insufficient balance");

        let to_balance: i128 = env
            .storage()
            .persistent()
            .get(&TokenDataKey::Balance(to.clone()))
            .unwrap_or(0);

        env.storage()
            .persistent()
            .set(&TokenDataKey::Balance(from), &(from_balance - amount));
        env.storage()
            .persistent()
            .set(&TokenDataKey::Balance(to), &(to_balance + amount));
    }

    pub fn balance(env: Env, owner: Address) -> i128 {
        env.storage()
            .persistent()
            .get(&TokenDataKey::Balance(owner))
            .unwrap_or(0)
    }

    pub fn approve(_env: Env, _from: Address, _spender: Address, _amount: i128, _expiration_ledger: u32) {
        // Simple approval - in real token this would be more complex
        // This is a placeholder for testing
    }
}

// ============================================================================
// TEST SETUP FUNCTIONS
// ============================================================================

/// Sets up a vault with mock token (no actual token contract)
pub fn setup_vault(env: &Env) -> (Address, Address, Address) {
    let contract_id = env.register_contract(None, NeuroWealthVault);
    let client = NeuroWealthVaultClient::new(env, &contract_id);

    let agent = Address::generate(env);
    let usdc_token = Address::generate(env);
    let owner = agent.clone();

    client.initialize(&agent, &usdc_token);

    (contract_id, agent, owner)
}

/// Sets up a vault with a real test token contract
pub fn setup_vault_with_token(env: &Env) -> (Address, Address, Address, Address) {
    let contract_id = env.register_contract(None, NeuroWealthVault);
    let client = NeuroWealthVaultClient::new(env, &contract_id);
    let agent = Address::generate(env);
    let usdc_token = env.register_contract(None, TestToken);
    let owner = agent.clone();

    client.initialize(&agent, &usdc_token);

    (contract_id, agent, owner, usdc_token)
}

/// Helper to find events by topic
pub fn find_events_by_topic(
    events: &Vec<(Vec<Val>, soroban_sdk::BytesN<32>, Val)>,
    env: &Env,
    topic: Symbol,
) -> Vec<(Vec<Val>, soroban_sdk::BytesN<32>, Val)>
{
    let mut result = Vec::new();
    for i in 0..events.len() {
        if let Some((topics, contract_id, data)) = events.get(i) {
            for j in 0..topics.len() {
                if let Some(t) = topics.get(j) {
                    if let Ok(s) = Symbol::try_from_val(env, t) {
                        if s == topic {
                            result.push((topics.clone(), *contract_id, data.clone()));
                            break;
                        }
                    }
                }
            }
        }
    }
    result
}

/// Helper to mint tokens and deposit in one step
pub fn mint_and_deposit(
    env: &Env,
    vault_client: &NeuroWealthVaultClient,
    token_address: &Address,
    user: &Address,
    amount: i128,
) {
    let token_client = soroban_sdk::contractclient!(TestToken).new(env, token_address);
    token_client.mint(user, &amount);
    vault_client.deposit(user, &amount);
}

// TestTokenClient is automatically generated by soroban_sdk::contractimpl
// The client type is created automatically when we use #[contractimpl]
